name: Build

on: [push, pull_request]

env:
  BUILD_TYPE: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build bindings on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build binaries
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel

      - uses: actions/upload-artifact@v3
        with:
          path: ${{github.workspace}}/build/*.so

      - uses: actions/upload-artifact@v3
        with:
          path: ${{github.workspace}}/build/${{env.BUILD_TYPE}}/*.pyd