name: Build

on: [push, pull_request]

env:
  BOOST_ROOT: ${{github.workspace}}/Boost
  DISTUTILS_DEBUG: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build bindings on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["windows-2019", "ubuntu-20.04"]
        python-version: ["3.6"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup requirements (Windows)
        if: matrix.os == 'windows-2019'
        run: |
          pip install oldest-supported-numpy
          curl -L -O https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.zip
          tar xfz boost_1_81_0.zip
          cd boost_1_81_0
          ./bootstrap.bat --with-python=python -prefix=${{env.BOOST_ROOT}}
          ./b2 variant=release address-model=32 link=static runtime-link=shared --with-python --build-type=minimal --prefix=${{env.BOOST_ROOT}} install

      - name: Setup requirements (Linux)
        if: matrix.os == 'ubuntu-20.04'
        run: |
          pip install oldest-supported-numpy
          curl -L -O https://boostorg.jfrog.io/artifactory/main/release/1.81.0/source/boost_1_81_0.tar.gz
          tar xfz boost_1_81_0.tar.gz
          cd boost_1_81_0
          ./bootstrap.sh --with-python=python -prefix=${{env.BOOST_ROOT}}
          ./b2 cxxflags=-fPIC variant=release address-model=64 link=static runtime-link=shared --with-python --build-type=minimal --prefix=${{env.BOOST_ROOT}} install

      - name: Build pyrocketsim wheels
        run: |
          pip install wheel
          python setup.py bdist_wheel --py-limited-api=cp36

      - uses: actions/upload-artifact@v3
        with:
          path: |
            ${{github.workspace}}/dist/*.whl